Fix exported types and update tooling
vtex-apps/device-detector pull request #16
Opened 2020-12-11 15:10 UTC by victorhmp

#### What problem is this solving?

Types exported by this app would resolve to `any` when other apps tried to use them.

#### How to test it?

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-11 17:42 UTC, klzns approved these changes

2020-12-14 13:55 UTC, kaisermann requested changes

2020-12-14 13:55 UTC, kaisermann commented on react/useDevice.tsx
> +export type Device = RenderContext.RenderContext['deviceInfo']['type']
Any reason to be exporting this?

2020-12-14 13:55 UTC, kaisermann commented on react/DeviceDetector.tsx
> +export type Device = RenderContext.RenderContext['deviceInfo']['type']
Any reason to be exporting this?

2020-12-14 15:19 UTC, victorhmp commented on react/useDevice.tsx
> +export type Device = RenderContext.RenderContext['deviceInfo']['type']
Nope. That's unnecessary :)

2020-12-14 15:19 UTC, victorhmp commented on react/DeviceDetector.tsx
> +export type Device = RenderContext.RenderContext['deviceInfo']['type']
Also unnecessary

2020-12-14 21:56 UTC, kaisermann approved these changes

2020-12-15 12:28 UTC, icazevedo approved these changes

2020-12-15 12:42 UTC, merged